### PR TITLE
impersonate command

### PR DESCRIPTION
**Pull request by InsaneCoder789**
Impersonate command for edith 

- A command which helps u to take the place of someone else
- very risky command( same as the risk ur mom took to give u birth)
-

### CODE REVIEW

**Comment by ItsNeil17** [comment]
Looking into this!

**Comment by TrueGamerTalha** [comment]
Did you copy it from sparta?

**Comment by InsaneCoder789** [comment]
yes somewhat ! 🤣

**Comment by InsaneCoder789** [comment]
see u need to apply brains for copy-pasta also 
as it requires a data file and a specified data to get to use

**Comment by InsaneCoder789** [comment]
@ItsNeil17  Just make the changes of "sparta" to "edith"
also @TrueGamerTalha  
- The sparta imp command is not owned by sparta
Circuit had also copied it from another repo.

**Review by ItsNeil17 — CHANGES_REQUESTED** [review]
Please add a .db (sqlite) file and then I'll be able to merge.

**Comment by ItsNeil17** [comment]
I meant that you should add the data.db file, where ever its supposed to be.

**Review by ItsNeil17 — APPROVED** [review]

**Review by ItsNeil17 — CHANGES_REQUESTED** [review]
Add a sqlite file where this data is stored in.

**Comment by InsaneCoder789** [comment]
> Add a sqlite file where this data is stored in.

Its in the main "data./_init_.py" file itself

**Comment by InsaneCoder789** [comment]
@ItsNeil17  That Data file will contain 
Both the sql database and the classmethod to excute the process

**Comment by ItsNeil17** [comment]
> > Add a sqlite file where this data is stored in.
> 
> Its in the main "data./_init_.py" file itself

What I mean like a data.db file, you know, it stores that data in a file and if that file isn't present it will just give you errors.

**Comment by InsaneCoder789** [comment]
> > > Add a sqlite file where this data is stored in.
> > 
> > 
> > Its in the main "data./_init_.py" file itself
> 
> What I mean like a data.db file, you know, it stores that data in a file and if that file isn't present it will just give you errors.

I know I am getting u
but here its of no need

**Review by ItsNeil17 — CHANGES_REQUESTED** [review]
Please add the `db.sqlite3` file!

**Comment by ItsNeil17** [comment]
> > > > Add a sqlite file where this data is stored in.
> > > 
> > > 
> > > Its in the main "data./_init_.py" file itself
> > 
> > 
> > What I mean like a data.db file, you know, it stores that data in a file and if that file isn't present it will just give you errors.
> 
> I know I am getting u but here its of no need

hmm okay, I'll run this code and see if it works. If it does then I'll accept this PR

**Comment by InsaneCoder789** [comment]
@ItsNeil17  I ADDED THE FILE!!!!

**Comment by ItsNeil17** [comment]
> @ItsNeil17 I ADDED THE FILE!!!!

Getting this error: discord.errors.ExtensionFailed: Extension 'cogs.slashfun' raised an error: ImportError: cannot import name 'Data' from 'cogs.data' (unknown location)

**Comment by ItsNeil17** [comment]
Try importing `data` instead of `cogs.data`

**Comment by ItsNeil17** [comment]
Also I still don't see the file in your code, maybe you forgot to push it?

**Comment by InsaneCoder789** [comment]
@ItsNeil17  I did push it

**Comment by ItsNeil17** [comment]
> @ItsNeil17 I did push it

Well I can't see it, and I just noticed your init files name is `_init_.py` it should be `__init__.py`

**Comment by ItsNeil17** [comment]
and  your indentation is all messed up

**Comment by InsaneCoder789** [comment]
@InsaneCoder789  i was doing this while solving a maths qp

**Comment by InsaneCoder789** [comment]
@ItsNeil17 
Sorry man
it should be `__init__,py` 
and all others are correct 
+ i have already pushed in the `db.sql` file

**Comment by ItsNeil17** [comment]
> @ItsNeil17 Sorry man it should be `__init__,py` and all others are correct
> 
>     * i have already pushed in the `db.sql` file

I don't see the file, check if you see it

**Comment by TrueGamerTalha** [comment]
@ItsNeil17 , @InsaneCoder789 is just a begginer in python like me lmao thats why he keeps messing up

**Comment by InsaneCoder789** [comment]
@TrueGamerTalha  true !

**Review by ItsNeil17 — DISMISSED** [review]
Thanks for fixing this! I'll test again and if it works I'll accept this PR.

**Comment by ItsNeil17** [comment]
Thanks for fixing this! I'll test again and if it works I'll accept this PR.

**Comment by ItsNeil17** [comment]
Getting this error: ```AttributeError: type object 'Data' has no attribute 'webhook_entry_exists'```, Please look into this and push when all the errors are fixed. If you're going to make another pull request later please first verify that your code works and then make a PR(Pull request)

**Pull request closed without merging**
