### PR TITLE
why did u revert the autosharding

### PR DESCRIPTION
**Pull request by ItsQuadrus**

### CODE REVIEW

**Comment by ItsQuadrus** [comment]
and why the hell did u remove my admin on the organisation u keep doing that back and forth

**Comment by ItsQuadrus** [comment]
im gonna give u a host

**Comment by ItsNeil17** [comment]
We don't need sharding right now, and if you want to give me a host contact me on discord: ItsNeil#0001

**Comment by ItsNeil17** [comment]
Also, it bugs out the server count & member count in /botinfo. I'll add it back when it's needed(if we get rate limited I'll add it back) and when I've fixed the server count and member count

**Pull request closed without merging**
